### ISSUE TITLE
ERROR: Failed to resolve: com.github.ueen:MorphButton:1.1

### ISSUE THREAD

**Issue by shivakishore** [ueen/MorphButton#1]
Cannot implement this repo

**Comment by ueen** [comment]
Hey, did you add jitpack.io as repository, as described in the README?

**Comment by shivakishore** [comment]
Yes. As is in README.

**Comment by ueen** [comment]
Here are the exact instructions https://jitpack.io/#ueen/MorphButton/1.1
Would you mind posting your project root build.gradle, just to check? :)

**Comment by ueen** [comment]
I believe this is a gradle setup problem and not a problem with the library.
